FROM websphere-liberty:javaee7
RUN apt-get update && apt-get install -y expect && rm -rf /var/lib/apt/lists/*
RUN installUtility install --acceptLicense clusterMember-1.0
COPY . /config/
CMD ["/bin/sh", "/config/startServer.sh"]
