FROM websphere-liberty:javaee7
RUN apt-get update && apt-get install -y openssh-server curl && rm -rf /var/lib/apt/lists/*
RUN installUtility install --acceptLicense clusterMember-1.0 scalingMember-1.0

COPY . /config/

RUN mkdir /var/run/sshd
RUN chmod 0755 /var/run/sshd
RUN echo 'root:screencast' | chpasswd
RUN sed -i 's/PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config
RUN sed -i "s/#PasswordAuthentication yes/PasswordAuthentication yes/" /etc/ssh/sshd_config
RUN sed 's@session\s*required\s*pam_loginuid.so@session optional pam_loginuid.so@g' -i /etc/pam.d/sshd

EXPOSE 22
EXPOSE 9080
EXPOSE 9443
CMD ["/config/startServer.sh"]
