version: "3"
services:
  controller:
    image: trajano/jee-controller:base
  webserver:
    image: trajano/jee-webserver:base
    deploy:
      replicas: 2
    depends_on: 
    - appserver
    ports: 
    - "80:80"
    - "443:443"
  appserver:
    image: trajano/jee-appserver:base
    deploy:
      replicas: 2
    depends_on: 
    - database
    - controller
  database:
    image: mariadb:latest
    volumes:
      - 'mariadb_data:/var/lib/mysql'
    environment:
      MYSQL_DATABASE: "jeesample"
      MYSQL_USER: "jeeuser"
      MYSQL_PASSWORD: "password"
      MYSQL_RANDOM_ROOT_PASSWORD: "true"
    ports: 
    - "33060:3306"
volumes:
  mariadb_data:
    driver: local