version: "3"
services:
  controller:
    image: trajano/jee-controller:base
    ports: 
    - "9443:9443"
    volumes:
    - 'collective_resources:/config/resources'
  # controller-replica:
  #   image: trajano/jee-controller:replica
  #   deploy:
  #     replicas: 2
  #   depends_on: 
  #   - controller
  #   volumes:
  #   - 'collective_resources:/controllerResources'
  webserver:
    image: trajano/jee-webserver:base
    deploy:
      replicas: 2
    depends_on: 
    - appserver
    ports: 
    - "80:80"
    - "443:443"
    volumes:
    - 'ihs_share:/share'
  appserver:
    image: trajano/jee-appserver:base
    deploy:
      replicas: 4
    depends_on: 
    - database
    - controller
  database:
    image: mariadb:latest
    volumes:
      - 'mariadb_data:/var/lib/mysql'
    environment:
      MYSQL_DATABASE: "jeesample"
      MYSQL_USER: "jeeuser"
      MYSQL_PASSWORD: "password"
      MYSQL_RANDOM_ROOT_PASSWORD: "true"
    ports: 
    - "33060:3306"
volumes:
  mariadb_data:
    driver: local
  collective_resources:
    driver: local
  ihs_share:
    driver: local