# FROM websphere-liberty:kernel
FROM websphere-liberty:javaee7
RUN installUtility install --acceptLicense collectiveController-1.0 adminCenter-1.0 scalingController-1.0
COPY . /config/
# RUN collective create defaultServer --keystorePassword=controllerKSPassword --createConfigFile=/config/collective-create-include.xml
CMD ["/bin/sh", "/config/startController.sh"]
