FROM websphere-liberty:javaee7
RUN apt-get update && apt-get install -y openssh-server && rm -rf /var/lib/apt/lists/*
RUN installUtility install --acceptLicense clusterMember-1.0 scalingMember-1.0

RUN mkdir /var/run/sshd
RUN chmod 0755 /var/run/sshd
RUN sed -i "s/#PasswordAuthentication yes/PasswordAuthentication yes/" /etc/ssh/sshd_config

EXPOSE 22
EXPOSE 9080
EXPOSE 9443
COPY startHost.sh /
CMD ["/startHost.sh"]
