FROM ibmcom/ibm-http-server:9.0.0.3

RUN apt-get update \
    && apt-get install -y --no-install-recommends unzip wget ca-certificates openssl \
    && rm -rf /var/lib/apt/lists/*

# Install WebSphere Liberty
ENV LIBERTY_VERSION 17.0.0_01
ARG LIBERTY_URL
ARG DOWNLOAD_OPTIONS=""
RUN LIBERTY_URL=${LIBERTY_URL:-$(wget -q -O - https://public.dhe.ibm.com/ibmdl/export/pub/software/websphere/wasdev/downloads/wlp/index.yml  | grep $LIBERTY_VERSION -A 6 | sed -n 's/\s*kernel:\s//p' | tr -d '\r' )}  \
    && wget $DOWNLOAD_OPTIONS $LIBERTY_URL -U UA-IBM-WebSphere-Liberty-Docker -O /tmp/wlp.zip \
    && unzip -q /tmp/wlp.zip -d /opt/ibm \
    && rm /tmp/wlp.zip
ENV JAVA_HOME=/opt/IBM/HTTPServer/java/8.0/jre \
    JVM_ARGS=-Dcom.ibm.webserver.plugin.utility.autoAcceptCertificates=true
RUN /opt/ibm/wlp/bin/installUtility install --acceptLicense restConnector-2.0 restConnector-1.0 dynamicRouting-1.0

# Cleanup
RUN apt-get purge -y unzip wget && apt-get -y autoremove && rm -rf /var/lib/apt/lists/*

# Add include to the configuration file
RUN mkdir -p /share /opt/IBM/WebSphere/Plugins/logs/webserver1
COPY startHttpServer.sh /work/
COPY defaultClusterPlugin.conf plugin-cfg.xml /opt/IBM/HTTPServer/conf/
RUN echo "Include /opt/IBM/HTTPServer/conf/defaultClusterPlugin.conf" >> /opt/IBM/HTTPServer/conf/httpd.conf

EXPOSE 80
EXPOSE 443
CMD ["/work/startHttpServer.sh"]
